const menuItems = [
    {
      id: 1,
      name: "망고",
      img: "/menu/crepes/DOR/OR1_mango.jpg",
      categories: "original",
      description: "망고 맛이 가득한 크레페입니다.",
    },
    {
      id: 2,
      name: "비나나",
      img: "/menu/crepes/DOR/OR1_바나나.jpg",
      categories: "original",
      description: "달콤한 바나나로 가득한 크레페입니다.",
    },
    {
      id: 3,
      name: "블베",
      img: "/menu/crepes/DOR/OR1_블베.jpg",
      categories: "original",
      description: "부드러운 블루베리 크림이 들어간 크레페입니다.",
    },
    {
      id: 4,
      name: "생딸기",
      img: "/menu/crepes/DOR/OR1_생딸기.jpg",
      categories: "original",
      description: "신선한 딸기로 만든 크레페입니다.",
    },
    {
      id: 5,
      name: "샤인1",
      img: "/menu/crepes/DOR/OR1_샤인.jpg",
      categories: "original",
      description: "고소한 샤인맛이 느껴지는 크레페입니다.",
    },
    {
      id: 6,
      name: "요거트블베",
      img: "/menu/crepes/DOR/OR1_요거트블베.jpg",
      categories: "original",
      description: "상큼한 요거트와 블루베리가 어우러진 크레페입니다.",
    },
    {
      id: 7,
      name: "뉴욕",
      img: "/menu/crepes/DOR/OR2_뉴욕.jpg",
      categories: "original",
      description: "뉴욕 치즈케이크를 담은 크레페입니다.",
    },
    {
      id: 8,
      name: "로투스",
      img: "/menu/crepes/DOR/OR2_로투스.jpg",
      categories: "original",
      description: "달콤한 로투스 크림이 들어간 크레페입니다.",
    },
    {
      id: 9,
      name: "몰티",
      img: "/menu/crepes/DOR/OR2_몰티.jpg",
      categories: "original",
      description: "부드러운 몰티 크림이 들어간 크레페입니다.",
    },
    {
      id: 10,
      name: "약과",
      img: "/menu/crepes/DOR/OR2_약과.jpg",
      categories: "original",
      description: "달콤한 약과 크림이 들어간 크레페입니다.",
    },
    {
      id: 11,
      name: "오레오",
      img: "/menu/crepes/DOR/OR2_오레오.jpg",
      categories: "original",
      description: "오레오 쿠키가 들어간 크레페입니다.",
    },
    {
      id: 12,
      name: "누텔라스모어",
      img: "/menu/crepes/DOR/OR3_누텔라스모어.jpg",
      categories: "original",
      description: "누텔라와 스모어가 들어간 크레페입니다.",
    },
    {
      id: 13,
      name: "딥커스터드",
      img: "/menu/crepes/DOR/OR3_누텔라스모어.jpg",
      categories: "original",
      description: "진한 커스터드 크림이 들어간 크레페입니다.",
    },
    {
      id: 14,
      name: "딥커스터드",
      img: "/menu/crepes/DOR/OR4_딥커스터드.jpg",
      categories: "original",
      description: "진한 커스터드 크림이 들어간 크레페입니다.",
    },
    {
      id: 15,
      name: "말차생크림",
      img: "/menu/crepes/DOR/OR4_말차생크림.jpg",
      categories: "original",
      description: "고소한 말차생크림이 들어간 크레페입니다.",
    },
    {
      id: 16,
      name: "자바칩",
      img: "/menu/crepes/DOR/OR4_자바칩.jpg",
      categories: "original",
      description: "커피맛과 초콜릿칩이 들어간 크레페입니다.",
    },
    {
      id: 17,
      name: "팬케익",
      img: "/menu/crepes/DOR/OR4_팬케익.jpg",
      categories: "original",
      description: "부드러운 팬케익 크림이 들어간 크레페입니다.",
    },
  ];


export default menuItems;